# Generated by Django 4.2.6 on 2024-02-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_alter_complaint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
